import { createEstimate } from "./lib/calculator.js";
import "./lib/services/ec2.js";
import "./lib/services/s3.js";
import "./lib/services/lambda.js";
import "./lib/services/dynamodb.js";
import "./lib/services/api-gateway.js";
import "./lib/services/cloudfront.js";
import "./lib/services/appsync.js";
import "./lib/services/athena.js";
import "./lib/services/bedrock.js";
import "./lib/services/bedrock-agentcore.js";
import "./lib/services/cloudtrail.js";
import "./lib/services/cloudwatch.js";
import "./lib/services/cognito.js";
import "./lib/services/ecr.js";
import "./lib/services/eventbridge.js";
import "./lib/services/glue.js";
import "./lib/services/redshift.js";
import "./lib/services/s3-vectors.js";
import "./lib/services/sagemaker-async.js";
import "./lib/services/secrets-manager.js";
import "./lib/services/step-functions.js";
import "./lib/services/systems-manager.js";
import "./lib/services/textract.js";
import "./lib/services/vpn.js";
import "./lib/services/waf.js";
import "./lib/services/xray.js";

export { createEstimate };
